// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: publisher.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Represents a public key
nonisolated struct Publisher_V3_PublicKey: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The key ID
  var keyID: UInt32 = 0

  /// The public key (32 bytes)
  var publicKey: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request message for getting the OAuth2 authorization URL
///
/// Required headers:
///   X-Payload-bin:    Encrypted request payload ciphertext (binary)
///   X-Public-Key-bin: Client ephemeral public key (eC_pk, 32 bytes, binary)
///   X-Key-ID:         Server identity key ID used for encrypting the payload (string)
///   X-Nonce-bin:      Request nonce (16 bytes, binary)
///   X-Timestamp:      Unix timestamp in seconds (string)
nonisolated struct Publisher_V3_GetOAuth2AuthorizationUrlRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The platform for which the authorization URL is requested
  var platform: String = String()

  /// Optional state parameter to prevent CSRF attacks
  var state: String = String()

  /// Optional PKCE code verifier. Ignored if autogenerate_code_verifier is true.
  var codeVerifier: String = String()

  /// If true, a PKCE code verifier is auto-generated and code_verifier is ignored
  var autogenerateCodeVerifier: Bool = false

  /// Optional redirect URL for the OAuth2 application
  var redirectURL: String = String()

  /// Optional request identifier for tracking
  var requestIdentifier: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response message for GetOAuth2AuthorizationUrl
nonisolated struct Publisher_V3_GetOAuth2AuthorizationUrlResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The authorization URL to redirect the user to
  var authorizationURL: String = String()

  /// State parameter for CSRF protection
  var state: String = String()

  /// PKCE code verifier (auto-generated or echo of the request value)
  var codeVerifier: String = String()

  /// A response message
  var message: String = String()

  /// Scope of the authorization request
  var scope: String = String()

  /// Client ID of the OAuth2 application
  var clientID: String = String()

  /// Redirect URL of the OAuth2 application
  var redirectURL: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request message for exchanging an OAuth2 authorization code for a token
///
/// Required headers:
///   X-Payload-bin:    Encrypted request payload ciphertext (binary)
///   X-Public-Key-bin: Client ephemeral public key (eC_pk, 32 bytes, binary)
///   X-Key-ID:         Server identity key ID used for encrypting the payload (string)
///   X-Nonce-bin:      Request nonce (16 bytes, binary)
///   X-Timestamp:      Unix timestamp in seconds (string)
nonisolated struct Publisher_V3_ExchangeOAuth2CodeAndStoreRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The platform for which the token exchange is being performed
  var platform: String = String()

  /// The authorization code received from the authorization server
  var authorizationCode: String = String()

  /// Optional PKCE code verifier
  var codeVerifier: String = String()

  /// Optional redirect URL for the OAuth2 application
  var redirectURL: String = String()

  /// Optional request identifier for tracking
  var requestIdentifier: String = String()

  /// Client ephemeral public keys to associate with the stored token
  var clientEphemeralPublicKeys: [Publisher_V3_PublicKey] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response message for ExchangeOAuth2CodeAndStore
nonisolated struct Publisher_V3_ExchangeOAuth2CodeAndStoreResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicates if the token exchange and storage was successful
  var success: Bool = false

  /// A response message
  var message: String = String()

  /// Account identifier associated with the token
  var accountIdentifier: String = String()

  /// Encrypted token ciphertext
  var tokenCiphertext: Data = Data()

  /// Unique identifier of the stored token
  var tokenID: UInt32 = 0

  /// Server ephemeral public keys associated with the token
  var serverEphemeralPublicKeys: [Publisher_V3_PublicKey] = []

  /// Key ID used for encrypting the token ciphertext
  var keyID: UInt32 = 0

  /// The platform name
  var platform: String = String()

  /// Category identifier
  var catID: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request message for revoking an OAuth2 token
///
/// Required headers:
///   X-Payload-bin:    Encrypted request payload ciphertext (binary)
///   X-Public-Key-bin: Client ephemeral public key (eC_pk, 32 bytes, binary)
///   X-Key-ID:         Server identity key ID used for encrypting the payload (string)
///   X-Nonce-bin:      Request nonce (16 bytes, binary)
///   X-Timestamp:      Unix timestamp in seconds (string)
nonisolated struct Publisher_V3_RevokeOAuth2TokenRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The unique identifier of the stored token
  var tokenID: UInt32 = 0

  /// The key ID used for encrypting the token in the payload
  var keyID: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response message for RevokeOAuth2Token
nonisolated struct Publisher_V3_RevokeOAuth2TokenResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicates if the token revocation and deletion was successful
  var success: Bool = false

  /// A response message
  var message: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request message for getting the PNBA code
///
/// Required headers:
///   X-Payload-bin:    Encrypted request payload ciphertext (binary)
///   X-Public-Key-bin: Client ephemeral public key (eC_pk, 32 bytes, binary)
///   X-Key-ID:         Server identity key ID used for encrypting the payload (string)
///   X-Nonce-bin:      Request nonce (16 bytes, binary)
///   X-Timestamp:      Unix timestamp in seconds (string)
nonisolated struct Publisher_V3_GetPNBACodeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The platform for which the PNBA code is requested
  var platform: String = String()

  /// The phone number for the platform
  var phoneNumber: String = String()

  /// Optional request identifier for tracking the request
  var requestIdentifier: String = String()

  /// The medium used to deliver the code (e.g., "whatsapp", "telegram", "signal").
  var channel: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response message for getting the PNBA code
nonisolated struct Publisher_V3_GetPNBACodeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicates if the request was successful
  var success: Bool = false

  /// A response message
  var message: String = String()

  /// Optional code expiry, Unix epoch seconds
  var expiresAt: Int64 {
    get {_expiresAt ?? 0}
    set {_expiresAt = newValue}
  }
  /// Returns true if `expiresAt` has been explicitly set.
  var hasExpiresAt: Bool {self._expiresAt != nil}
  /// Clears the value of `expiresAt`. Subsequent reads from it will return its default value.
  mutating func clearExpiresAt() {self._expiresAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _expiresAt: Int64? = nil
}

/// Request message for exchanging the PNBA code for a token and storing it
///
/// Required headers:
///   X-Payload-bin:    Encrypted request payload ciphertext (binary)
///   X-Public-Key-bin: Client ephemeral public key (eC_pk, 32 bytes, binary)
///   X-Key-ID:         Server identity key ID used for encrypting the payload (string)
///   X-Nonce-bin:      Request nonce (16 bytes, binary)
///   X-Timestamp:      Unix timestamp in seconds (string)
nonisolated struct Publisher_V3_ExchangePNBACodeAndStoreRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The platform for which the token exchange is being performed
  var platform: String = String()

  /// The phone number for the platform
  var phoneNumber: String = String()

  /// The authorization code received from the platform
  var authorizationCode: String = String()

  /// The password for two-step verification
  var password: String = String()

  /// Optional request identifier for tracking the request
  var requestIdentifier: String = String()

  /// Client ephemeral public keys to associate with the stored token
  var clientEphemeralPublicKeys: [Publisher_V3_PublicKey] = []

  /// The medium used to receive the code (e.g., "whatsapp", "telegram", "signal").
  var channel: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response message for exchanging the PNBA code for a token and storing it
nonisolated struct Publisher_V3_ExchangePNBACodeAndStoreResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicates if the request was successful
  var success: Bool = false

  /// A response message
  var message: String = String()

  /// Indicates if two step verification is enabled
  var twoStepVerificationEnabled: Bool = false

  /// Account identifier associated with the token
  var accountIdentifier: String = String()

  /// Encrypted token ciphertext
  var tokenCiphertext: Data = Data()

  /// Unique identifier of the stored token
  var tokenID: UInt32 = 0

  /// Server ephemeral public keys associated with the token
  var serverEphemeralPublicKeys: [Publisher_V3_PublicKey] = []

  /// Key ID used for encrypting the token ciphertext
  var keyID: UInt32 = 0

  /// The platform name
  var platform: String = String()

  /// Category identifier
  var catID: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request message for revoking and deleting a PNBA token
///
/// Required headers:
///   X-Payload-bin:    Encrypted request payload ciphertext (binary)
///   X-Public-Key-bin: Client ephemeral public key (eC_pk, 32 bytes, binary)
///   X-Key-ID:         Server identity key ID used for encrypting the payload (string)
///   X-Nonce-bin:      Request nonce (16 bytes, binary)
///   X-Timestamp:      Unix timestamp in seconds (string)
nonisolated struct Publisher_V3_RevokePNBATokenRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The unique identifier of the stored token
  var tokenID: UInt32 = 0

  /// The key ID used for encrypting the token in the payload
  var keyID: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response message for revoking and deleting a PNBA token
nonisolated struct Publisher_V3_RevokePNBATokenResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A response message.
  var message: String = String()

  /// Indicates whether the operation was successful.
  var success: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request message for syncing key pools for a token
///
/// Required headers:
///   X-Payload-bin:    Encrypted request payload ciphertext (binary)
///   X-Public-Key-bin: Client ephemeral public key (eC_pk, 32 bytes, binary)
///   X-Key-ID:         Server identity key ID used for encrypting the payload (string)
///   X-Nonce-bin:      Request nonce (16 bytes, binary)
///   X-Timestamp:      Unix timestamp in seconds (string)
nonisolated struct Publisher_V3_SyncKeysRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The unique identifier of the stored token
  var tokenID: UInt32 = 0

  /// The key ID used for encrypting the token in the payload
  var keyID: UInt32 = 0

  /// Client ephemeral public keys to associate with the stored token
  var clientEphemeralPublicKeys: [Publisher_V3_PublicKey] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response message for SyncKeys
nonisolated struct Publisher_V3_SyncKeysResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicates if the sync was successful
  var success: Bool = false

  /// A response message
  var message: String = String()

  /// Server ephemeral public keys associated with the token
  var serverEphemeralPublicKeys: [Publisher_V3_PublicKey] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "publisher.v3"

nonisolated extension Publisher_V3_PublicKey: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PublicKey"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}key_id\0\u{3}public_key\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.keyID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.publicKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.keyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyID, fieldNumber: 1)
    }
    if !self.publicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicKey, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_PublicKey, rhs: Publisher_V3_PublicKey) -> Bool {
    if lhs.keyID != rhs.keyID {return false}
    if lhs.publicKey != rhs.publicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_GetOAuth2AuthorizationUrlRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetOAuth2AuthorizationUrlRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}platform\0\u{1}state\0\u{3}code_verifier\0\u{3}autogenerate_code_verifier\0\u{3}redirect_url\0\u{3}request_identifier\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.codeVerifier) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.autogenerateCodeVerifier) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.redirectURL) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.requestIdentifier) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 1)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 2)
    }
    if !self.codeVerifier.isEmpty {
      try visitor.visitSingularStringField(value: self.codeVerifier, fieldNumber: 3)
    }
    if self.autogenerateCodeVerifier != false {
      try visitor.visitSingularBoolField(value: self.autogenerateCodeVerifier, fieldNumber: 4)
    }
    if !self.redirectURL.isEmpty {
      try visitor.visitSingularStringField(value: self.redirectURL, fieldNumber: 5)
    }
    if !self.requestIdentifier.isEmpty {
      try visitor.visitSingularStringField(value: self.requestIdentifier, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_GetOAuth2AuthorizationUrlRequest, rhs: Publisher_V3_GetOAuth2AuthorizationUrlRequest) -> Bool {
    if lhs.platform != rhs.platform {return false}
    if lhs.state != rhs.state {return false}
    if lhs.codeVerifier != rhs.codeVerifier {return false}
    if lhs.autogenerateCodeVerifier != rhs.autogenerateCodeVerifier {return false}
    if lhs.redirectURL != rhs.redirectURL {return false}
    if lhs.requestIdentifier != rhs.requestIdentifier {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_GetOAuth2AuthorizationUrlResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetOAuth2AuthorizationUrlResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}authorization_url\0\u{1}state\0\u{3}code_verifier\0\u{1}message\0\u{1}scope\0\u{3}client_id\0\u{3}redirect_url\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.authorizationURL) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.codeVerifier) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.scope) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.clientID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.redirectURL) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.authorizationURL.isEmpty {
      try visitor.visitSingularStringField(value: self.authorizationURL, fieldNumber: 1)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 2)
    }
    if !self.codeVerifier.isEmpty {
      try visitor.visitSingularStringField(value: self.codeVerifier, fieldNumber: 3)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 4)
    }
    if !self.scope.isEmpty {
      try visitor.visitSingularStringField(value: self.scope, fieldNumber: 5)
    }
    if !self.clientID.isEmpty {
      try visitor.visitSingularStringField(value: self.clientID, fieldNumber: 6)
    }
    if !self.redirectURL.isEmpty {
      try visitor.visitSingularStringField(value: self.redirectURL, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_GetOAuth2AuthorizationUrlResponse, rhs: Publisher_V3_GetOAuth2AuthorizationUrlResponse) -> Bool {
    if lhs.authorizationURL != rhs.authorizationURL {return false}
    if lhs.state != rhs.state {return false}
    if lhs.codeVerifier != rhs.codeVerifier {return false}
    if lhs.message != rhs.message {return false}
    if lhs.scope != rhs.scope {return false}
    if lhs.clientID != rhs.clientID {return false}
    if lhs.redirectURL != rhs.redirectURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_ExchangeOAuth2CodeAndStoreRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ExchangeOAuth2CodeAndStoreRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}platform\0\u{3}authorization_code\0\u{3}code_verifier\0\u{3}redirect_url\0\u{3}request_identifier\0\u{3}client_ephemeral_public_keys\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.authorizationCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.codeVerifier) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.redirectURL) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.requestIdentifier) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.clientEphemeralPublicKeys) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 1)
    }
    if !self.authorizationCode.isEmpty {
      try visitor.visitSingularStringField(value: self.authorizationCode, fieldNumber: 2)
    }
    if !self.codeVerifier.isEmpty {
      try visitor.visitSingularStringField(value: self.codeVerifier, fieldNumber: 3)
    }
    if !self.redirectURL.isEmpty {
      try visitor.visitSingularStringField(value: self.redirectURL, fieldNumber: 4)
    }
    if !self.requestIdentifier.isEmpty {
      try visitor.visitSingularStringField(value: self.requestIdentifier, fieldNumber: 5)
    }
    if !self.clientEphemeralPublicKeys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.clientEphemeralPublicKeys, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_ExchangeOAuth2CodeAndStoreRequest, rhs: Publisher_V3_ExchangeOAuth2CodeAndStoreRequest) -> Bool {
    if lhs.platform != rhs.platform {return false}
    if lhs.authorizationCode != rhs.authorizationCode {return false}
    if lhs.codeVerifier != rhs.codeVerifier {return false}
    if lhs.redirectURL != rhs.redirectURL {return false}
    if lhs.requestIdentifier != rhs.requestIdentifier {return false}
    if lhs.clientEphemeralPublicKeys != rhs.clientEphemeralPublicKeys {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_ExchangeOAuth2CodeAndStoreResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ExchangeOAuth2CodeAndStoreResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}account_identifier\0\u{3}token_ciphertext\0\u{3}token_id\0\u{3}server_ephemeral_public_keys\0\u{3}key_id\0\u{1}platform\0\u{3}cat_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accountIdentifier) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.tokenCiphertext) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.tokenID) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.serverEphemeralPublicKeys) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self.keyID) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.catID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.accountIdentifier.isEmpty {
      try visitor.visitSingularStringField(value: self.accountIdentifier, fieldNumber: 3)
    }
    if !self.tokenCiphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.tokenCiphertext, fieldNumber: 4)
    }
    if self.tokenID != 0 {
      try visitor.visitSingularUInt32Field(value: self.tokenID, fieldNumber: 5)
    }
    if !self.serverEphemeralPublicKeys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.serverEphemeralPublicKeys, fieldNumber: 6)
    }
    if self.keyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyID, fieldNumber: 7)
    }
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 8)
    }
    if self.catID != 0 {
      try visitor.visitSingularUInt32Field(value: self.catID, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_ExchangeOAuth2CodeAndStoreResponse, rhs: Publisher_V3_ExchangeOAuth2CodeAndStoreResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.accountIdentifier != rhs.accountIdentifier {return false}
    if lhs.tokenCiphertext != rhs.tokenCiphertext {return false}
    if lhs.tokenID != rhs.tokenID {return false}
    if lhs.serverEphemeralPublicKeys != rhs.serverEphemeralPublicKeys {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.catID != rhs.catID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_RevokeOAuth2TokenRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RevokeOAuth2TokenRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}token_id\0\u{3}key_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.tokenID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.keyID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tokenID != 0 {
      try visitor.visitSingularUInt32Field(value: self.tokenID, fieldNumber: 1)
    }
    if self.keyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_RevokeOAuth2TokenRequest, rhs: Publisher_V3_RevokeOAuth2TokenRequest) -> Bool {
    if lhs.tokenID != rhs.tokenID {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_RevokeOAuth2TokenResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RevokeOAuth2TokenResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_RevokeOAuth2TokenResponse, rhs: Publisher_V3_RevokeOAuth2TokenResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_GetPNBACodeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetPNBACodeRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}platform\0\u{3}phone_number\0\u{3}request_identifier\0\u{1}channel\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.phoneNumber) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.requestIdentifier) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.channel) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 1)
    }
    if !self.phoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.phoneNumber, fieldNumber: 2)
    }
    if !self.requestIdentifier.isEmpty {
      try visitor.visitSingularStringField(value: self.requestIdentifier, fieldNumber: 3)
    }
    if !self.channel.isEmpty {
      try visitor.visitSingularStringField(value: self.channel, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_GetPNBACodeRequest, rhs: Publisher_V3_GetPNBACodeRequest) -> Bool {
    if lhs.platform != rhs.platform {return false}
    if lhs.phoneNumber != rhs.phoneNumber {return false}
    if lhs.requestIdentifier != rhs.requestIdentifier {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_GetPNBACodeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetPNBACodeResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}expires_at\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self._expiresAt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try { if let v = self._expiresAt {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_GetPNBACodeResponse, rhs: Publisher_V3_GetPNBACodeResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs._expiresAt != rhs._expiresAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_ExchangePNBACodeAndStoreRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ExchangePNBACodeAndStoreRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}platform\0\u{3}phone_number\0\u{3}authorization_code\0\u{1}password\0\u{3}request_identifier\0\u{3}client_ephemeral_public_keys\0\u{1}channel\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.phoneNumber) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.authorizationCode) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.password) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.requestIdentifier) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.clientEphemeralPublicKeys) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.channel) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 1)
    }
    if !self.phoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.phoneNumber, fieldNumber: 2)
    }
    if !self.authorizationCode.isEmpty {
      try visitor.visitSingularStringField(value: self.authorizationCode, fieldNumber: 3)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 4)
    }
    if !self.requestIdentifier.isEmpty {
      try visitor.visitSingularStringField(value: self.requestIdentifier, fieldNumber: 5)
    }
    if !self.clientEphemeralPublicKeys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.clientEphemeralPublicKeys, fieldNumber: 6)
    }
    if !self.channel.isEmpty {
      try visitor.visitSingularStringField(value: self.channel, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_ExchangePNBACodeAndStoreRequest, rhs: Publisher_V3_ExchangePNBACodeAndStoreRequest) -> Bool {
    if lhs.platform != rhs.platform {return false}
    if lhs.phoneNumber != rhs.phoneNumber {return false}
    if lhs.authorizationCode != rhs.authorizationCode {return false}
    if lhs.password != rhs.password {return false}
    if lhs.requestIdentifier != rhs.requestIdentifier {return false}
    if lhs.clientEphemeralPublicKeys != rhs.clientEphemeralPublicKeys {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_ExchangePNBACodeAndStoreResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ExchangePNBACodeAndStoreResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}two_step_verification_enabled\0\u{3}account_identifier\0\u{3}token_ciphertext\0\u{3}token_id\0\u{3}server_ephemeral_public_keys\0\u{3}key_id\0\u{1}platform\0\u{3}cat_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.twoStepVerificationEnabled) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.accountIdentifier) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.tokenCiphertext) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.tokenID) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.serverEphemeralPublicKeys) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.keyID) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 10: try { try decoder.decodeSingularUInt32Field(value: &self.catID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.twoStepVerificationEnabled != false {
      try visitor.visitSingularBoolField(value: self.twoStepVerificationEnabled, fieldNumber: 3)
    }
    if !self.accountIdentifier.isEmpty {
      try visitor.visitSingularStringField(value: self.accountIdentifier, fieldNumber: 4)
    }
    if !self.tokenCiphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.tokenCiphertext, fieldNumber: 5)
    }
    if self.tokenID != 0 {
      try visitor.visitSingularUInt32Field(value: self.tokenID, fieldNumber: 6)
    }
    if !self.serverEphemeralPublicKeys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.serverEphemeralPublicKeys, fieldNumber: 7)
    }
    if self.keyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyID, fieldNumber: 8)
    }
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 9)
    }
    if self.catID != 0 {
      try visitor.visitSingularUInt32Field(value: self.catID, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_ExchangePNBACodeAndStoreResponse, rhs: Publisher_V3_ExchangePNBACodeAndStoreResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.twoStepVerificationEnabled != rhs.twoStepVerificationEnabled {return false}
    if lhs.accountIdentifier != rhs.accountIdentifier {return false}
    if lhs.tokenCiphertext != rhs.tokenCiphertext {return false}
    if lhs.tokenID != rhs.tokenID {return false}
    if lhs.serverEphemeralPublicKeys != rhs.serverEphemeralPublicKeys {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.catID != rhs.catID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_RevokePNBATokenRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RevokePNBATokenRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}token_id\0\u{3}key_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.tokenID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.keyID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tokenID != 0 {
      try visitor.visitSingularUInt32Field(value: self.tokenID, fieldNumber: 1)
    }
    if self.keyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_RevokePNBATokenRequest, rhs: Publisher_V3_RevokePNBATokenRequest) -> Bool {
    if lhs.tokenID != rhs.tokenID {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_RevokePNBATokenResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RevokePNBATokenResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}message\0\u{1}success\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_RevokePNBATokenResponse, rhs: Publisher_V3_RevokePNBATokenResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.success != rhs.success {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_SyncKeysRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SyncKeysRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}token_id\0\u{3}key_id\0\u{3}client_ephemeral_public_keys\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.tokenID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.keyID) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.clientEphemeralPublicKeys) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tokenID != 0 {
      try visitor.visitSingularUInt32Field(value: self.tokenID, fieldNumber: 1)
    }
    if self.keyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyID, fieldNumber: 2)
    }
    if !self.clientEphemeralPublicKeys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.clientEphemeralPublicKeys, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_SyncKeysRequest, rhs: Publisher_V3_SyncKeysRequest) -> Bool {
    if lhs.tokenID != rhs.tokenID {return false}
    if lhs.keyID != rhs.keyID {return false}
    if lhs.clientEphemeralPublicKeys != rhs.clientEphemeralPublicKeys {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Publisher_V3_SyncKeysResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SyncKeysResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0\u{3}server_ephemeral_public_keys\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.serverEphemeralPublicKeys) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.serverEphemeralPublicKeys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.serverEphemeralPublicKeys, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Publisher_V3_SyncKeysResponse, rhs: Publisher_V3_SyncKeysResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.serverEphemeralPublicKeys != rhs.serverEphemeralPublicKeys {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
